"""create interview questions table

Revision ID: a69a49c13379
Revises: dc722ae0c206
Create Date: 2026-08-18 10:14:16.117858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69a49c13379'
down_revision: Union[str, Sequence[str], None] = 'dc722ae0c206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_match_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_category'), 'interview_questions', ['category'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_match_id'), 'interview_questions', ['job_match_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_resume_id'), 'interview_questions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_user_id'), 'interview_questions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_user_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_resume_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_job_match_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_category'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
